[package]
name = "cargo-machete"
edition = "2021"
version = "0.1.0"
description = "Find unused dependencies with this one weird trick!"
authors = [ "Benjamin Bouvier <public@benj.me>" ]
repository = "https://github.com/bnjbvr/cargo-machete"
keywords = []
categories = []
license = "MIT/Apache-2.0"

[dependencies]
cargo_toml = "0.10.1"
grep = "0.2.8"
log = "0.4.14"
pretty_env_logger = "0.4.0"
toml = "0.5.8"
walkdir = "2.3.2"
anyhow = "1.0.47"
rayon = "1.5.1"

# Uncomment this for profiling.
#[profile.release]
#debug = true
