[package]
name = "cargo-machete"
edition = "2021"
version = "0.6.0"
description = "Find unused dependencies with this one weird trick!"
authors = ["Benjamin Bouvier <public@benj.me>"]
repository = "https://github.com/bnjbvr/cargo-machete"
keywords = []
categories = []
license = "MIT"
readme = "README.md"

[dependencies]
anyhow = "1.0.57"
cargo_metadata = "0.18.0"
cargo_toml = "0.16.2"
clap = { version = "4.4.11", features = ["derive", "cargo"] }
grep = "0.2.8"
log = "0.4.16"
pretty_env_logger = "0.5.0"
rayon = "1.5.2"
serde = "1.0.136"
toml_edit = "0.20.0"
walkdir = "2.3.2"

# Uncomment this for profiling.
#[profile.release]
#debug = true
